language: erlang

otp_release:
  - 19.2

sudo: false

#notifications:
#  email: false

addons:
  apt:
    packages:
    - git

before_script:
  - set -e
  - git clone --depth 1 --branch cl-1.2.3 https://github.com/tonyrog/cl.git
  - export ERL_LIBS=`pwd`
  - export MAKEFLAGS=-j6

script:
  - make

after_success:
  - dialyzer --build_plt --apps erts kernel stdlib wx tools xmerl --statistics
  - dialyzer -n -Wno_improper_lists ebin/*.beam plugins/accel/*.beam plugins/autouv/*.beam plugins/commands/*.beam plugins/default/*.beam plugins/import_export/*.beam plugins/primitives/*.beam --statistics

# Needs a compiled cl-1.2.3
#after_script:
#  - make unix
